enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "both"
patches-source = "anddea/revanced-patches"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
patches-source = "anddea/revanced-patches"

[GooglePhotos]
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
enabled = "false"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
version = "auto"
patches-source = "anddea/revanced-patches"
rv-brand = "ReVanced Andea"
build-mode = "apk"
arch = "arm64-v8a"
